### ISSUE TITLE
Analytics Not Calculating Properly

### ISSUE THREAD

**Issue by Unovamata** [Unovamata/Neopets-Shop-And-Attic-Autobuyer-Cracked#1]
• Analytics are not calculated properly whenever there's an item missing from the database that does not contains an "Estimated Profit".

Currently, there's a workaround to show the data inside the "Analytics" tab in the "History" tab, but more testing needs to be done in order to fix it.

Mainly, the error occurs whenever there's an undefined value or string as an "Estimated Profit" as that value requires to be casted as an integer. Since it can't be parsed, the system cannot continue calculating the averages and data for the "Analytics" tab, causing the error. Try and catches have been added, but that does not fixes the problem outright.

The "Analytics" segment of the code inside "history.js" may need a revamp to circumvent that difficulty.

**Comment by Unovamata** [comment]
Update: In version 0.53.2, the "Analytics" option has been removed. It will be restored in the near future.

**Comment by Neo-Dobby** [comment]
Hi, I'm writing here since I didn't know where else to contact you. I have noticed that quite often I'm failing to get an iteam because on the haggling page, NeoBuys clicks on the image before writing the price, so it gets stuck there. Is there any setting that we can specify after how many ms to click the image? So it gives time to write the price first before clicking the captcha image.

**Comment by Unovamata** [comment]
It seems this has been a common issue along the users of NeoBuyer+ thanks to the new 0.6v update. Please refer to issue https://github.com/Unovamata/Neopets-Shop-And-Attic-Autobuyer-Cracked/issues/19 .

You can configure those times here:

![image](https://github.com/Unovamata/Neopets-Shop-And-Attic-Autobuyer-Cracked/assets/91705840/a9ca6559-2b81-4943-b912-5c282313282b)

I will fix it in the following days. Thanks for the detailed report.

I hope you continue to use NeoBuyer+, I'm very sorry about this issue. Please refer to the issue linked above for further discussion. Thanks.

**Comment by Unovamata** [comment]
Analytics are now working as expected and they will be released in the next 0.7 version of the extension.
