### ISSUE TITLE
Problem updating prices on multiple pages

### ISSUE THREAD

**Issue by lecanardcolvert** [Unovamata/Neopets-Shop-And-Attic-Autobuyer-Cracked#12]
I have at least two pages of items in my shop.
When I click 'Submit Prices', then the prices in the first page are set.
Then, I get the popup 'Since you deactivated the Auto-Enter PIN option...'
I click OK, then the next page is immediately loaded before I can click on Update.
When I go back to the first page, the prices are not set.

For now, I have to update a maximum of 30 items at a time.
Edit: Even if I check less than 30 items, the next page is immediately loaded and I can't save the prices in the first page.

**Comment by Unovamata** [comment]
I'll look into it, thank you for your input.

I'll fix this bug in the next update of the extension. Thank you very much.

**Comment by Unovamata** [comment]
This issue has been fixed in the next to release version of the extension. Now the extension waits for the user to input a valid PIN until it updates the prices.

Thank you very much for your help.
