### ISSUE TITLE
I can't get this autobuyer to do anything

### ISSUE THREAD

**Issue by jmg3195** [Unovamata/Neopets-Shop-And-Attic-Autobuyer-Cracked#14]
Hi, I've repeatedly tried to get this autobuyer to work with zero success. I'm not sure what the problem is but I have it turned on, I'm signed into neopets, and I have the shop I'm trying to buy from open in a tab. How do I get this to work?

**Comment by Unovamata** [comment]
Hi jmg! Please follow this post: [https://github.com/Unovamata/Neopets-Shop-And-Attic-Autobuyer-Cracked/issues/13](Tutorial).

It seems some users are having that same problem, so I'll make the AutoBuyer easier to setup in the next update. For now, can you tell me if the guide above helps you on anything?

If you get any console errors, please send them on this issue so I can guide you through them / fix them.
Thank you for your help and I'm very sorry for the inconvenience I have caused.

**Comment by jmg3195** [comment]
That link doesn't lead to a page with a guide

**Comment by Unovamata** [comment]
Oh, my bad! Try again, I updated the link.

**Comment by jmg3195** [comment]
This is what I'm seeing 
![image](https://github.com/Unovamata/Neopets-Shop-And-Attic-Autobuyer-Cracked/assets/51762894/2014cddb-4175-4056-9a3c-06e8f997d67e)

**Comment by Unovamata** [comment]
Whenever you see an "inject.js" error in the main shops, send it here. As the image attached is an error within the Neopets page.

Can you see the "X" stocked items on the shop tab? Be sure to also activate the banner for confirmation.

**Comment by jmg3195** [comment]
I'm not sure what you mean... it's doing absolutely nothing.

**Comment by jmg3195** [comment]
Where would I see "X" stocked items on the shop tab?

**Comment by jmg3195** [comment]
Ah never mind I see what you meant and no I'm not seeing the "X" stocked items on the shop tab

**Comment by Unovamata** [comment]
The shop title should look something like this:

![image](https://github.com/Unovamata/Neopets-Shop-And-Attic-Autobuyer-Cracked/assets/91705840/5ccc414d-07cf-44dc-9503-f16e177974f0)

Can you activate the AutoBuyer? Are you using a custom list or are you using DB estimates?

**Comment by jmg3195** [comment]
Yes it's activated it just not doing anything. I've tried both a custom list and DB estimates right now it's on DB estimates

**Comment by jmg3195** [comment]
I looked through the entire guide there was nothing pertinent to my issue

**Comment by Unovamata** [comment]
Can you show me an screenshot of this option?

![image](https://github.com/Unovamata/Neopets-Shop-And-Attic-Autobuyer-Cracked/assets/91705840/0e7f5bb6-1965-4420-95b6-9a16c91cddcb)

Also, can you send me another screenshot of the console but this time, browsing various shops? Be sure to censor any sensitive information.

**Comment by jmg3195** [comment]
![image](https://github.com/Unovamata/Neopets-Shop-And-Attic-Autobuyer-Cracked/assets/51762894/78713963-b4a0-4aee-88ce-26e635761cb7)

the console is blank now for every shop I visit

**Comment by jmg3195** [comment]
It does load my shops stock

**Comment by Unovamata** [comment]
[Are you running version 0.53.9?](https://github.com/Unovamata/Neopets-Shop-And-Attic-Autobuyer-Cracked/releases/tag/0.53.9v) As the code in the repository is not ready for release.

It seems the extension may be working as expected, but your inject script is not, but it is quite odd, as there are no errors on the console.

Is this option activated in the AutoBuyer page?

![image](https://github.com/Unovamata/Neopets-Shop-And-Attic-Autobuyer-Cracked/assets/91705840/486390b6-5c8c-49c7-a20a-3ab9ad3eca99)

**Comment by jmg3195** [comment]
Yes I'm running 0.53.9

**Comment by jmg3195** [comment]
Yes that option is enabled

**Comment by Unovamata** [comment]
Ok, in the AutoBuyer page do the following:

• Ctrl + S.
• Save the HTML file.
• Send the saved HTML file here.

**Comment by jmg3195** [comment]
It won't let me attach it, it says that file type isn't supported

**Comment by Unovamata** [comment]
You can upload it here: https://www.file.io

What browser are you using?

**Comment by jmg3195** [comment]
Chrome

**Comment by jmg3195** [comment]
![image](https://github.com/Unovamata/Neopets-Shop-And-Attic-Autobuyer-Cracked/assets/51762894/88c0b3e6-5c9f-4ea3-a4e0-a8f34a62e976)
![image](https://github.com/Unovamata/Neopets-Shop-And-Attic-Autobuyer-Cracked/assets/51762894/882fb525-1c4c-45b9-b766-972c0913fe06)
![image](https://github.com/Unovamata/Neopets-Shop-And-Attic-Autobuyer-Cracked/assets/51762894/cbf7eca0-49f6-420d-b90b-1f56dcc721b5)
![image](https://github.com/Unovamata/Neopets-Shop-And-Attic-Autobuyer-Cracked/assets/51762894/9148bbf6-5d9b-427d-add0-c200021599e4)
![image](https://github.com/Unovamata/Neopets-Shop-And-Attic-Autobuyer-Cracked/assets/51762894/0eb50a84-8312-4615-aa8c-b7f82a82b4c1)

**Comment by Unovamata** [comment]
Ok, I think I see where the problem may be. But for now, can you click on the **"Reset All Settings"** button and go to the shop you want to stock?

**Comment by Unovamata** [comment]
Try to also deactivate the banner, just in case.

**Comment by jmg3195** [comment]
I reset all settings and turned off "Show Status Banner" and still nothing

**Comment by Unovamata** [comment]
Not even the "X" stocked items?

Are you changing any value after resetting the settings? Use the default values if possible to test this issue.

Can you send me another screenshot but this time, can you show me your chrome extension window? chrome://extensions/

**Comment by Unovamata** [comment]
This issue may be browser specific, I suggest you redownload google chrome and update it to the latest version. Maybe that will fix it.

You haven't changed anything within the files or deleted any script?

**Comment by jmg3195** [comment]
Not even the "X' stocked items, no the only setting I changed was turning off "Show Status Banner" everything else I left the way it was after resetting. No I haven't changed any files or deleted any script. My chrome is already updated to the latest.

**Comment by jmg3195** [comment]
![image](https://github.com/Unovamata/Neopets-Shop-And-Attic-Autobuyer-Cracked/assets/51762894/faee49ef-676c-408e-a9c4-2ded42ea025b)

**Comment by jmg3195** [comment]
These are the only extensions I have and only the NeoBuyer+ and uBlock Origin are activated

**Comment by jmg3195** [comment]
Google chrome info:
Chrome is up to date
Version 118.0.5993.71 (Official Build) (64-bit)

**Comment by Unovamata** [comment]
> These are the only extensions I have and only the NeoBuyer+ and uBlock Origin are activated

Can you deactivate uBlock Origin? I think that may be blocking the execution of the extension, but I'm not sure.

Try testing the extension with a clean instalation of Opera or Chronium

**Comment by jmg3195** [comment]
Disabling uBlock Origin did nothing I also uninstalled chrome and reinstalled it with no luck either

**Comment by Unovamata** [comment]
Alright, I think you may need to install another browser. 

I suggest either Opera or Opera GX for testing purposes.

**Comment by jmg3195** [comment]
I tried Opera and it also didn't work. I've also tried brave and edge.

**Comment by Unovamata** [comment]
Have you acknowledge the warning the extension has?

**Comment by jmg3195** [comment]
Yes

**Comment by Unovamata** [comment]
I ran out of ideas, I think this may be on your end as the AutoPricer works as expected. 

Redownload the files, extract them, and then load the folder containing the extension with its new files, as I have exhausted all possibilities in this specific use case.

**Comment by jmg3195** [comment]
Well I've tried that and still no dice.

**Comment by Unovamata** [comment]
Are you on incognito?

**Comment by Unovamata** [comment]
The extension has been updated once again. I forgot to activate the AutoBuyer when I removed a paywall error a couple of this ago, this has been fixed.

Thanfully, this problem won't happen again, as the next version release will contain a more optimized and usable AutoBuyer.

I'm deeply sorry for the confusion caused. I have thoroughly tested this version, so it won't give you any trouble.
Once again, sorry and thank you for your patience.

**Comment by jmg3195** [comment]
So are you saying it's fixed in version 0.53.10v?

**Comment by jmg3195** [comment]
![image](https://github.com/Unovamata/Neopets-Shop-And-Attic-Autobuyer-Cracked/assets/51762894/aafcbe0c-76bf-4ade-a89e-785d022a3750)
![image](https://github.com/Unovamata/Neopets-Shop-And-Attic-Autobuyer-Cracked/assets/51762894/c7ef4a6a-f17f-449f-9c86-ac2b883113ce)

I did try 0.53.10V with no luck and I feel like maybe this is the problem? Although I checked the extension settings and they appear to be fine?

**Comment by Unovamata** [comment]
Indeed the issue was fixed on version 0.53.10v. 
The access is not related to the issue. I have installed version 0.53.10v in another browser for testing purposes and it has worked without problems.
Be sure to check if the "'X' stocked items", banner, and auto-clicking capabilities appear in the page. Try to also lower the DB estimates to buy an item, as if those values are too high, the extension may not buy the items. Also try with a restocking list or adding the name of an item already in the shop you're browsing to test the program.

Here's a photo of the extension working in version 0.53.10v:

![image](https://github.com/Unovamata/Neopets-Shop-And-Attic-Autobuyer-Cracked/assets/91705840/d94fb0cd-555a-4494-958e-8c2198e9f32e)

So this problem may be related on how are you setting up the extension and its times. Try to check if there are any "inject.js" errors in the console and send them here.

**Comment by jmg3195** [comment]
What browser did you test it in? I tried chrome and edge. Also how do I find the console and where would I see an "inject.js" error? I'm happy to check I just don't know where to find that info

**Comment by Unovamata** [comment]
Don't worry about it! I know it can be quite difficult to find the console. You can check issue https://github.com/Unovamata/Neopets-Shop-And-Attic-Autobuyer-Cracked/issues/13 to see a thorough guide on how to find the browser's console.

I tested the extension in [Chronium](https://download-chromium.appspot.com), Chrome, and Opera, but mainly Chronium.

**Comment by jmg3195** [comment]
I will test out Chronium and check out issue #13 and hopefully I can get it to work :) I appreciate your help

**Comment by jmg3195** [comment]
Oh 1 more question I should be downloading the NeoBuyer.0.53.10.rar file and extracting it correct?

**Comment by Unovamata** [comment]
If nothing else works, try to wait for version 0.6v. I will be releasing it either today or tomorrow, so it may be a compatibility issue with the old version of the script, as the new auto-buyer script is more streamlined and optimized. So keep and eye out for that.

As for the .rar question, yes. You should download and extract the extension every time you have to download or update the extension manually. Maybe in the next release I will make it so users don't have to extract it.

**Comment by jmg3195** [comment]
Great news! It works in Chronium! :) Do you have any guides regarding configuring settings for the autobuyer? I just want to make sure I'm not setting them to settings that will get me frozen

**Comment by Unovamata** [comment]
Actually! Can you send me the browser versions you have? It would be a nice case study for me to see if the extension doesn't works in some specific browser versions. Though, if you didn't extracted the .rar file that may be the reason why the extension wasn't working, but I'm not 100% sure haha.

I would like to refrain from answering that question, in the next version release you will be able to browse through a FAQs page, where it contains the information you're looking for, to cite the page: 

"_We'd prefer not to provide a specific answer to that question._ TNT keeps logs that track restocking activities, so it can raise suspicion if they observe a large number of new users displaying the speed and proficiency of experienced restockers.

 A safe approach is to begin with a set of settings and gradually adjust them over time. _It is advisable to avoid clicking items within a 50-millisecond timeframe and to refrain from rapid haggling within 100 milliseconds._ Actions that closely resemble human behavior are less likely to result in account suspensions."

I'm glad I could be of help! I hope you enjoy the extension and its current and future features! Best of luck 😄!

**Comment by jmg3195** [comment]
Oh I have been using the .rar file and extracting it before adding it as an extension :) I just wanted to make sure that what I was doing was correct. For Chrome I was using Version 118.0.5993.89 (Official Build) (64-bit). For Edge I was using Version 118.0.2088.57 (Official build) (64-bit). Totally understandable thank you for all of your help! I'm so excited to be able to use it :)

**Comment by Unovamata** [comment]
Awesome! Thank you for your insightful information, I will be checking those versions in some hours to provide a proper fix to these issues you have been experiencing.
