### ISSUE TITLE
updating

### ISSUE THREAD

**Issue by Nickwarlick** [Unovamata/Neopets-Shop-And-Attic-Autobuyer-Cracked#16]
having trouble updating ive tried redownloading the files but cant get the update?

**Comment by Unovamata** [comment]
Can you describe to me the process you're going through?
Do you still get the "NeoBuyer+ is not updated" message when you replace the files?

Remember that version 0.53.10 is the newest version and that you must replace all files in your directory. Your options will be intact if you do this.

If you're curious about version 0.6 and it's release, it will be released shortly, but build 0.6 hasn't been released yet as I'm polishing some aspects to give the users the best experience possible.

**Comment by Nickwarlick** [comment]
i replaced the inject file and its working now, thank you but when you try to click the latest download it says this 404 - page not found
The 
527fa0941a04a257235a8dce8123d35020441154

 branch of 
Neopets-Shop-And-Attic-Autobuyer-Cracked

 does not contain the path 
github.com/Unovamata/Neopets-Shop-And-Attic-Autobuyer-Cracked/releases/latest.

**Comment by Nickwarlick** [comment]
sorry im new to downloading chrome extensions from elsewhere

**Comment by Unovamata** [comment]
No worries, I completely understand how complicated this entire process can be, so feel free to ask as many questions as you need, it will be my pleasure to help you.

It seems you have downloaded only the inject file needed for AutoBuying, I highly suggest you reinstall the extension and wait for the new version release, as version 0.53.10 is the most stable iteration of the project at this point and time. The code you have downloaded is not yet ready for release, but I appreciate your excitement.

I'm very sorry if I provided a link that does not works. For the time being, please download [Version 0.53.10](https://github.com/Unovamata/Neopets-Shop-And-Attic-Autobuyer-Cracked/releases/tag/0.53.10v) and repeat the installation process once again.

I will sort this issue as soon as I have some time available, thank you for using NeoBuyer+! Please reopen or comment on this issue for any further support.
