### ISSUE TITLE
AutoAttic "AutoRefreshAttic()" function missing.

### ISSUE THREAD

**Issue by gameaholic115** [Unovamata/Neopets-Shop-And-Attic-Autobuyer-Cracked#18]
AutoAttic dosn't seem to work it goes says autobuyer running but never Refresh on its own with Refresh Automatically on.

**Comment by Unovamata** [comment]
Have you set the Attic's last refresh time? 
![image](https://github.com/Unovamata/Neopets-Shop-And-Attic-Autobuyer-Cracked/assets/91705840/dbd373c8-218b-4024-b2e3-4d6fa59748c8)


As far as I know the attic has been broken since TNT fixed the NST time.

Can you provide more details for this error? Is there anything on the console?

**Comment by gameaholic115** [comment]
No I didn’t set the last refresh time but on the vs I used before the last update it was working with the banner saying when it would refresh the page but now it’s only saying auto buyer running Sent from my iPhoneOn Oct 27, 2023, at 12:45 PM, Daoko ***@***.***> wrote:﻿
Have you set the Attic's last refresh time?

As far as I know the attic has been broken since TNT fixed the NST time.
Can you provide more details for this error? Is there anything on the console?

**Comment by Unovamata** [comment]
No worries! The error has been fixed! 

Thank you for your report, I forgot to type the AutoRefreshing snippet of code that allowed the AutoBuyer to refresh on the Almost Abandoned Attic automatically.

Thank you so much for your support.
Happy AutoBuying! 😄

**Comment by gameaholic115** [comment]
Ok can you please let me know when you have it fixed and if I need to download something Sent from my iPhoneOn Oct 27, 2023, at 4:03 PM, Daoko ***@***.***> wrote:﻿
No worries! The error has been fixed!
Thank you for your report, I forgot to type the AutoRefreshing snippet of code that allowed the AutoBuyer to refresh on the Almost Abandoned Attic automatically.
Thank you so much for your support.
Happy AutoBuying! 😄

**Comment by Unovamata** [comment]
It has already been fixed. Please download version 0.6.1v from the latest release in the repository.

Thank you for your support.

**Comment by gameaholic115** [comment]
Cool thanks I’ll get it when I get home Sent from my iPhoneOn Oct 27, 2023, at 4:16 PM, Daoko ***@***.***> wrote:﻿
It has already been fixed. Please download version 0.6.1v from the latest release in the repository.
Thank you for your support.
