### ISSUE TITLE
Link to the new version not working

### ISSUE THREAD

**Issue by galfink** [Unovamata/Neopets-Shop-And-Attic-Autobuyer-Cracked#20]
The first link in the neobuyer+ is not working, and does not redirect to the 6.1 version

**Comment by Unovamata** [comment]
Can you be more specific about where this link is located? Is it in the ReadMe? The mails? Somewhere else?

Thank you for reporting the error!

**Comment by galfink** [comment]
Download the **[Latest Version of NeoBuyer+](https://github.com/Unovamata/Neopets-Shop-And-Attic-Autobuyer-Cracked/blob/main/github.com/Unovamata/Neopets-Shop-And-Attic-Autobuyer-Cracked/releases/latest)** from the releases page and save these files to any location on your computer.

That bold part isn't working

**Comment by galfink** [comment]
Sorry if i was a little "harsh", english is not my mother language. But in read.me
The first part of the "how to install"

1. "Download the [Latest Version of NeoBuyer+](https://github.com/Unovamata/Neopets-Shop-And-Attic-Autobuyer-Cracked/blob/main/github.com/Unovamata/Neopets-Shop-And-Attic-Autobuyer-Cracked/releases/latest) from the releases page and save these files to any location on your computer.

The **latest version of Neobuyer** isn't working the link

**Comment by Unovamata** [comment]
No worries! You did not sound harsh at all! 

That is a very simple fix, someone reported the error a while back and I thought I had already fixed it, my bad!

Thank you so much for reporting the issue, I hope you continue to use NeoBuyer+!

Happy AutoBuying!
