### ISSUE TITLE
Cannot install extension with .crx file in Microsoft Edge

### ISSUE THREAD

**Issue by lecanardcolvert** [Unovamata/Neopets-Shop-And-Attic-Autobuyer-Cracked#21]
I tried installing the extension (.crx file) in Microsoft Edge but got this error.

![screenshot_12](https://github.com/Unovamata/Neopets-Shop-And-Attic-Autobuyer-Cracked/assets/59675854/9ae27c35-a2d9-48b1-a035-9b83ca5aa75b)

**Comment by Unovamata** [comment]
Are you double-clicking the extension or dragging and dropping it in the Extensions page?

It seems this is a documented issue with Chronium-based browsers, so I will try to have a workaround for it.

https://support.google.com/chrome/thread/7757612/what-does-crx-required-proof-missing-mean-when-trying-to-install-a-chrome-extension?hl=en

**Comment by Unovamata** [comment]
Can you check if the newest .crx file fixes the issue for me? Thank you very much!

**Comment by Unovamata** [comment]
Since no answer was provided and the .crx file was changed. I will assume the problem has been fixed. Thank you for your report and your continuous support.

**Comment by Unovamata** [comment]
Have you tried in other browsers? Chronium or Google Chrome for instance?

**Comment by Unovamata** [comment]
You only need to drag-and-drop the file. Most Chronium browsers remove the option, but if you drag them in to the browser window, you can definitely install it! Correct me if I am wrong, as I do not use Chrome regularly.

**Comment by Unovamata** [comment]
No worries! Thank you for your input, I have removed the .cry installation altogether.

As I said before this is a known issue with Chronium based browsers, but it is most likely something on my end that it is changing the extension's compressed data.

I will continue to push releases using the .rar file installation method.

Thank you very much for your input and testing. I hope you continue to use NeoBuyer+ for a long time.
