### ISSUE TITLE
Restock list

### ISSUE THREAD

**Issue by Tarcigrota** [Unovamata/Neopets-Shop-And-Attic-Autobuyer-Cracked#23]
Hello. Thank you very much, this helps me a lot! I would like to know how to manually add items to the restock list, because in the database I can only find the ready list and cannot edit it.
I would like to take this opportunity to ask about the most updated version. I received an email when I installed this version, asking me to update to 0.61.7v but I couldn't find it here... thanks again.

**Comment by Tarcigrota** [comment]
Sorry for my ignorance but I'm a new user and I'm still learning. What configuration do you use to get a nice amount of items? Because I left it on yesterday from 6 am to 8 pm (switching accounts) and only purchased 3 items. I saw in the history that many items were sold. I think I didn't configure it correctly, what can I adjust?

**Comment by Unovamata** [comment]
Sorry for not answering your issue, I have been quite busy lately.

I'm glad you're enjoying the project! If you want to create a restock list you can use Jellyneo's database or the [Shop Directory](https://www.jellyneo.net/?go=shopsdirectory) page JellyNeo has. I will add this resource in a future update.

The current most recent update is version [0.65.13v](https://github.com/Unovamata/Neopets-Shop-And-Attic-Autobuyer-Cracked/releases). Version 0.61.7v has been deprecated and no longer maintained. 

The NeoBuyer+'s mail is only a way for me to communicate with users if Neopets does any policy or code structure changes. be sure to always check the date of these mails, if it is not a recent date, then you can ignore it.

**Comment by Unovamata** [comment]
You can check the FAQ page under the Tools > Miscellaneous > NeoBuyer's FAQ to obtain more information about our stance sharing information about the AutoBuyer's most optimized settings.

Sorry if this is not the answer you were looking for. We would be risking our entire userbase if we shared the details on how to get the most optimized settings. These settings should be yours and yours only, but you can always share configuration presets with other NeoBuyer+'s users.

Thank you for being so patient and understanding. I hope you continue to enjoy NeoBuyer+ for the foreseeable future. 😄
