### ISSUE TITLE
manifest error

### ISSUE THREAD

**Issue by maydaysamuel** [Unovamata/Neopets-Shop-And-Attic-Autobuyer-Cracked#24]
@Unovamata 
I am getting this error:

~/Downloads/Neopets-Shop-And-Attic-Autobuyer-Cracked-0.65.13v/Autobuyer
Error
Could not load javascript 'src/SDBPricer.js' for content script.
Could not load manifest.

**Comment by Unovamata** [comment]
Hi! Sorry for the late response.

Are you downloading the [latest release](https://github.com/Unovamata/Neopets-Shop-And-Attic-Autobuyer-Cracked/releases/tag/0.65.13v)? 

If you download the repository's files, you are bound to get errors as the repository consists of code not ready for release. Still, if you download the newest version of the extension from the releases page you would be able to install the extension without any problems! 😄 

Let me know if this does not fixes the issue, I would be glad to help! Thank you for using NeoBuyer+.

**Comment by maydaysamuel** [comment]
That is where I downloaded from and it did not fix the issue. It still gives me the error. I am using Chrome on a Mac. Do I need to be using the .rar file?

**Comment by Unovamata** [comment]
I am glad the problem was solved! Do not worry about anything!

I am happy you are using NeoBuyer+, so thank you for your support.
