### ISSUE TITLE
Restock list generator suggestion

### ISSUE THREAD

**Issue by KainoaM** [Unovamata/Neopets-Shop-And-Attic-Autobuyer-Cracked#28]
Some shops have pages and pages of items you might want on the list. Copying and pasting them all can get very tedious. 

The print button seen here will bring you to a page with all items.

<img width="901" alt="image" src="https://github.com/Unovamata/Neopets-Shop-And-Attic-Autobuyer-Cracked/assets/71083484/07606952-aee3-4cc9-9fe0-8f423ef0d5f3">

Perhaps copying this entire page and pasting into the generator can be a more convenient option

<img width="1137" alt="image" src="https://github.com/Unovamata/Neopets-Shop-And-Attic-Autobuyer-Cracked/assets/71083484/7d990dfc-c6d2-4e72-a526-3375d854edfc">

**Comment by Unovamata** [comment]
Amazing contribution! Thank you very much for this! I will add support for this page in the next update! Thank you very much!

**Comment by Unovamata** [comment]
Version 0.7.7.2 has been released supporting this feature specifically.

Thank you very much for your contribution, I hope you continue to use NeoBuyer in the forseeable future. Happy AutoBuying!

**Comment by KainoaM** [comment]
You are the best!!!!

**Comment by Unovamata** [comment]
No worries!  Thank you for your support! If you would like to star the project it would be a great help for me!

I wish you a happy AutoBuying! Thank you for your amazing suggestion.
