### ISSUE TITLE
Multiaccount setup question

### ISSUE THREAD

**Issue by chrisli-03** [Unovamata/Neopets-Shop-And-Attic-Autobuyer-Cracked#38]
Hi, in the program there are mensions of using multiple accounts, how would I set that up? I have a few shell accounts I want to use. Thank you

**Comment by Unovamata** [comment]
Hi Chris! The extension supports the usage of multiple accounts to load and parse data for analytics. I personally do not support multiple account usage with NeoBuyer+ as this can deter the experience for other users.

I am personally not aware of this method myself, so I would not be able to answer that question thoroughly. Still, NeoBuyer+ is meant for its usage in one account, so any large scale botting would not be supported. I hope you understand.

**Comment by chrisli-03** [comment]
> Hi Chris! The extension supports the usage of multiple accounts to load and parse data for analytics. I personally do not support multiple account usage with NeoBuyer+ as this can deter the experience for other users.
> 
> I am personally not aware of this method myself, so I would not be able to answer that question thoroughly. Still, NeoBuyer+ is meant to be used in one account, so any large scale botting would not be supported. I hope you understand.

THank you for the clarification
