### ISSUE TITLE
AutoPricer cannot start

### ISSUE THREAD

**Issue by lecanardcolvert** [Unovamata/Neopets-Shop-And-Attic-Autobuyer-Cracked#4]
Hello,

First of all, thank you for this project.

I am having an issue with AutoPricer. First I loaded all my items in the inventory.
Then, I click on **Start Autopricing**. A new tab opens, the status changes for **Navigating to SW**.
Then, nothing. It just loads indefinitely.

Here is the error.

![Screenshot_1](https://github.com/Unovamata/Neopets-Shop-And-Attic-Autobuyer-Cracked/assets/59675854/b0150e74-61bb-4fe7-ba02-ead9220e2f1a)

Thanks.

**Comment by Unovamata** [comment]
No worries! I'm glad you're liking the project!

Noted! I'll fix that either today or tomorrow by doing a fresh install on another browser for proper bug testing. I'm sorry if it has cause any inconvenience. 

It may be something on how the variables are defined by default. Have you tried filling the blacklist with anything? Does that fixes the problem?

Thank you for taking the time to report the issue.

**Comment by Unovamata** [comment]
Fixed! Thank you for your help!

Be sure to do a fresh install, as it may be needed to update the default variables in the GUI.
