### ISSUE TITLE
Minimum 5 second rule refresh

### ISSUE THREAD

**Issue by Dvger** [Unovamata/Neopets-Shop-And-Attic-Autobuyer-Cracked#40]
Hi there, I have noticed that we can no longer change the minimum 5 second rule refresh timing (or rather the change does not retain after refreshing the page) after the most recent updates. May I know if there is any way to work around this issue, or was it intended this way? Thank you.

**Comment by Unovamata** [comment]
Hello Dvger. Firstly, I will like to thank you for using NeoBuyer+, I am very happy you are enjoying the work I have done in the extension.

You are right, this feature seems to not be working properly in the NeoBuyer+ GUI. Thank you for your report. I will try to push an update whenever I have some free time. Thank you very much!

**Comment by Unovamata** [comment]
Thank you for your report! This has been fixed in the newest version release.

I hope you continue to use NeoBuyer+ in the foreseeable future. 😊
