### ISSUE TITLE
Attic

### ISSUE THREAD

**Issue by neopetsa** [Unovamata/Neopets-Shop-And-Attic-Autobuyer-Cracked#41]
I had been wondering for a while if this could be an issue but waited until I could confirm it, which is today.

The way attic works is that it when it restocks it will stock the 24 items one by one, in very rapid succession, but 1 by 1 none the less. Meaning that you could refresh the page and catch the restock when it has only partially stocked with for example 10 items. This is actually beneficial for when it comes to buying items fast but it creates a problem with the code because it will think another restock happened the next time it reloads the shop and the remaining items appear.
So when that happens it will update the last restock time incorrectly to the time where it refreshed and saw the remaining items of the restock.

I bought an item at 3/18/2024, 4:13:38 PM, which was when it refreshed super well timed and only saw about half of the items. 
Then it refreshed once more at the end of the possible restock cycle (it always does that) and noticed more items stocked, so it set the restock time to 4:14:01 or so. which means its now 23 seconds too late with any future restocks.

A possible fix would be to not allow it to update restock time twice in under 14 minutes?
Another fix would be to refresh one extra time after a restock happened to make sure it caught the whole thing (all 24 items load in aproximately 100-200 ms if i had to guess so 1 extra refresh should always catch the whole thing)

As always contact me on discord if this was not clear.

**Comment by Unovamata** [comment]
Thank you for your report! This issue has been fixed in commit #https://github.com/Unovamata/Neopets-Shop-And-Attic-Autobuyer-Cracked/commit/7d4fc83e02aaa21d1684535aa41a6f7d6b99dd8e.

Thank you very much for your continuous support. I hope you continue to use NeoBuyer+ for the foreseeable future.
