### ISSUE TITLE
autopricer doesnt work

### ISSUE THREAD

**Issue by nslepak** [Unovamata/Neopets-Shop-And-Attic-Autobuyer-Cracked#45]
hi, i'm wondering if the autopricer doesn't work for just me or if it's broken for everyone. i can import my shop stock and check/uncheck items, but  when i start the autopricer, it just opens the shop wizard and gets stuck. hoping that its something fixable cuz boy is pricing stuff a lot of effort lol. thank you!

oh also is there any way to have it price over the lowest price instead of lower than?

**Comment by Unovamata** [comment]
Are you using version [0.7.20.27v](https://github.com/Unovamata/Neopets-Shop-And-Attic-Autobuyer-Cracked/releases/tag/0.7.20.27v) from the releases page? If that is the case, please refer to [FAQ #2](https://github.com/Unovamata/Neopets-Shop-And-Attic-Autobuyer-Cracked/wiki/FAQs) to report the error with further information. Thank you very much. :)

For your question about pricing, please refer to the AutoPricer's Manual page. All the options are thoroughly explained but if you still have any questions please return to this issue and report if you did not understand the
