### ISSUE TITLE
Captcha not working 

### ISSUE THREAD

**Issue by raychongtv** [Unovamata/Neopets-Shop-And-Attic-Autobuyer-Cracked#47]
For some reason this captcha is not working. Click on the red dot result in wrong position. 
![image](https://github.com/Unovamata/Neopets-Shop-And-Attic-Autobuyer-Cracked/assets/91705840/545f7fb4-4726-41dc-90c7-ebe91f7ce111)

(Issue censored to protect the user's identity).

**Comment by Unovamata** [comment]
Hi Raychongtv, thank you for your report. The AutoHaggling process will fail the captcha image click occasionally, as it is challenging to solve this query correctly all the time.

This issue lets you camouflage your NeoBuyer+ usage activity. The AutoCaptcha solver clicks consistently the solicited pet 90% of the time, while the other 10% consists of images difficult to solve even for the most advanced captcha solvers.

At the moment, this feature is the best combination of performance and consistency but I will make sure to add this in the FAQs section of the extension to clarify this scenario.

Thank you so much. I hope you continue to use NeoBuyer+ in the foreseeable future.
