### ISSUE TITLE
Confirm Window?

### ISSUE THREAD

**Issue by 11nei** [Unovamata/Neopets-Shop-And-Attic-Autobuyer-Cracked#50]
Hi there, I have noticed that the activation of bypass confirm window not working. The confirm window still pop-up and wait for auto-click confirm to the haggling page. May I know if there is any way to work around this issue, or was it intended this way? Thank you.

**Comment by Unovamata** [comment]
You are right, I just noticed this issue. Thank you so much for your report. A new version will be release shortly to address this issue.

**Comment by 11nei** [comment]
Thanks for update! But it seems the confirm window still keeps popping up while AutoBuying, sad....

**Comment by Unovamata** [comment]
Interesting. Have you checked if you have the bypass option active? It should be marked as red when enabled. I will reopen the issue and check what is happening. Sorry for the inconvenience and thank you for your patience.

**Comment by Unovamata** [comment]
I have tested the code and even though the confirm window opens, the extension bypasses the confirm window by completely ignoring it. The confirm window opening is just a byproduct of the extension clicking the item for purchase.

Thank you for using NeoBuyer+. I hope you continue to use it in the foreseeable future!
