### ISSUE TITLE
Captcha page detected when it's a 504

### ISSUE THREAD

**Issue by lecanardcolvert** [Unovamata/Neopets-Shop-And-Attic-Autobuyer-Cracked#6]
I get the 'Captcha page detected' alert when it's only a 504 error.

![screenshot_3](https://github.com/Unovamata/Neopets-Shop-And-Attic-Autobuyer-Cracked/assets/59675854/e9895072-7fef-4413-8525-5ec8439832b7)

**Comment by Unovamata** [comment]
Fixed! This will be in effect in the next update.

Thank you for your help! If you still encounter the problem, please feel free to reopen this issue!
