### ISSUE TITLE
AutoPricer not detecting Shop Wizard ban (maybe?)

### ISSUE THREAD

**Issue by lecanardcolvert** [Unovamata/Neopets-Shop-And-Attic-Autobuyer-Cracked#7]
The AutoPricer doesn't detect a Shop Wizard ban. The last searched item is forever loading.

Here is an example.

![screenshot_4](https://github.com/Unovamata/Neopets-Shop-And-Attic-Autobuyer-Cracked/assets/59675854/1d15c371-ab41-430f-a98e-4f762636aa09)

![screenshot_5](https://github.com/Unovamata/Neopets-Shop-And-Attic-Autobuyer-Cracked/assets/59675854/8a9e4b2c-9b79-4075-90c1-86e004aa870a)

I know that there is a setting 'Minimum/Maximum wait time if Shop Wizard Banned' but I wonder if the AutoPricer detects it, because there is no message or alert about it.

Maybe the status should change to something like 'Shop Wizard banned, retrying in x minutes'.

**Comment by Unovamata** [comment]
Oh! That's a quite interesting find! Yes, the system detects and waits the specified time.
Oddly enough, that should display on the GUI as the state is set in the code as soon as that happens. 

So in short, yes. The extension waits for 'x' minutes, but I'm not sure why is it not displaying on the GUI. I'll work on a fix to it, thank you for your help!

**Comment by Unovamata** [comment]
The code has stayed the same, I tested the issue from a fresh install and an instalation that has quite a bit of time without problems.

Before the ban is detected, the extension waits for some seconds before continuing its execution, so if your wait times are high, you may not see an effect until you check NeoBuyer+'s GUI. 

Thankfully, now the system displays an alert or a pop-up to let the end-user know that the system has detected the SW ban correctly.
Remember to lower the SW wait times on NeoBuyer+'s AutoPricer GUI.
If you're still facing issues with SW Ban detection, please reopen this issue.

Thank you for your help! You're contributing to make NeoBuyer+ more user friendly. 😄
